In [59]:
import pandas as pd

## Small task for taking unique issue (Task 2)

In [22]:
date_cols = ['date']

In [23]:
data = pd.read_csv('./Data/ccc_compiled_2017-2020_fipscompiled.csv', encoding = 'latin-1', low_memory=False, parse_dates=date_cols)

In [24]:
data

,date,bigevent,bydate,locality,state,location_detail,online,type,title,macroevent,...,countycountyequivalent,statename,fipsstatecode,fipscountycode,centraloutlyingcounty,_merge1,_merge2,_merge3,_merge4,zipcode
0,2017-01-01,NaN,1,Washington,DC,Lafayette Square Park,0.0,vigil,White House Peace Vigil,NaN,...,District of Columbia,District of Columbia,11.0,1.0,Central,Matched (3),NaN,NaN,NaN,NaN
1,2017-01-01,NaN,1,Mankato,MN,NaN,0.0,vigil,NaN,NaN,...,Blue Earth County,Minnesota,27.0,13.0,Central,Matched (3),NaN,NaN,NaN,NaN
2,2017-01-01,NaN,1,Minneapolis,MN,U.S. Bank Stadium,0.0,protest; banner drop,NaN,NaN,...,Hennepin County,Minnesota,27.0,53.0,Central,Matched (3),NaN,NaN,NaN,NaN
3,2017-01-01,NaN,1,Little Compton,RI,Town Green,0.0,vigil,NaN,NaN,...,Newport County,Rhode Island,44.0,5.0,Central,Matched (3),NaN,NaN,NaN,NaN
4,2017-01-01,NaN,1,Oak Ridge,TN,Y-12 National Security Complex,0.0,vigil,NaN,NaN,...,Anderson County,Tennessee,47.0,1.0,Central,Matched (3),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72069,2020-12-31,NaN,4,San Antonio,TX,The Alamo,0.0,rally,NaN,NaN,...,Bexar County,Texas,48.0,29.0,Central,NaN,NaN,NaN,Matched (3),NaN
72070,2020-12-31,NaN,4,San Antonio,TX,Piazza Italia Park,0.0,demonstration,NaN,NaN,...,Bexar County,Texas,48.0,29.0,Central,NaN,NaN,NaN,Matched (3),NaN
72071,2020-12-31,NaN,4,Norfolk,VA,Macarthur Square,0.0,demonstration,NaN,NaN,...,Norfolk city,Virginia,51.0,710.0,Central,NaN,NaN,NaN,Matched (3),NaN
72072,2020-12-31,NaN,4,Seattle,WA,Cal Anderson Park; King County Youth Services ...,0.0,demonstration,NaN,NaN,...,King County,Washington,53.0,33.0,Central,NaN,NaN,NaN,Matched (3),NaN
72073,2020-12-31,NaN,4,Seattle,WA,11th and Pine,0.0,vigil,NaN,NaN,...,King County,Washington,53.0,33.0,Central,NaN,NaN,NaN,Matched (3),NaN

In [ ]:
data.columns

Index(['date', 'bigevent', 'bydate', 'locality', 'state', 'location_detail',
       'online', 'type', 'title', 'macroevent', 'actors', 'organizations',
       'participants', 'claims', 'valence', 'issues', 'issues_major',
       'size_text', 'size_low', 'size_high', 'size_mean', 'size_cat',
       'arrests', 'arrests_any', 'injuries_crowd', 'injuries_crowd_any',
       'injuries_police', 'injuries_police_any', 'property_damage',
       'property_damage_any', 'chemical_agents', 'participant_measures',
       'police_measures', 'participant_deaths', 'police_deaths', 'source_1',
       'source_2', 'source_3', 'source_4', 'source_5', 'source_6', 'source_7',
       'source_8', 'source_9', 'source_10', 'source_11', 'source_12',
       'source_13', 'source_14', 'source_15', 'source_16', 'source_17',
       'source_18', 'source_19', 'source_20', 'source_21', 'source_22',
       'source_23', 'source_24', 'source_25', 'source_26', 'source_27',
       'source_28', 'source_29', 'source_30', 'notes', 'lat', 'lon',
       'resolved_locality', 'resolved_county', 'resolved_state', 'fips',
       'date_start', 'date_end', 'cbsa', 'metropolitandivisioncode', 'csacode',
       'cbsatitle', 'metropolitanmicropolitanstatisti',
       'metropolitandivisiontitle', 'csatitle', 'countycountyequivalent',
       'statename', 'fipsstatecode', 'fipscountycode', 'centraloutlyingcounty',
       '_merge1', '_merge2', '_merge3', '_merge4', 'zipcode'],
      dtype='object')

In [ ]:
data['issues']

0                                                 military
1                                                 military
2        banking and finance; economy; energy; environm...
3                              environment; guns; military
4                                                 military
                               ...
72069                                democracy; presidency
72070                                     criminal justice
72071                                     criminal justice
72072                            economy; policing; racism
72073                                     policing; racism
Name: issues, Length: 72074, dtype: object

In [ ]:
# Split the 'issues' column by ';' and expand into multiple columns
split_issues = data['issues'].str.split(';', expand=True)

In [ ]:
# Remove any extra whitespace from split values
split_issues = split_issues.apply(lambda x: x.str.strip())

In [ ]:
# Rename columns dynamically (issues1, issues2, issues3, ...)
split_issues.columns = [f'issues{i+1}' for i in range(split_issues.shape[1])]

In [ ]:
split_issues[split_issues['issues15'].notna()]

,issues1,issues2,issues3,issues4,issues5,issues6,issues7,issues8,issues9,issues10,issues11,issues12,issues13,issues14,issues15
69305,banking and finance,covid,democracy,economy,environment,healthcare,immigration,labor,lgbtqia,military,policing,presidency,racism,reproductive rights,women's rights

In [ ]:
data.iloc[69305]

date        2020-07-11 00:00:00
bigevent                    NaN
bydate                        4
locality               Columbus
state                        OH
                   ...
issues11               policing
issues12             presidency
issues13                 racism
issues14    reproductive rights
issues15         women's rights
Name: 69305, Length: 106, dtype: object

In [ ]:
# Flatten the DataFrame into a single list and remove NaN values
all_issues = pd.Series(split_issues.values.ravel()).dropna()

In [ ]:
# Get unique values from the list
unique_issues = all_issues.unique()

In [ ]:
# Create a new DataFrame with one column for the unique values
unique_issues_df = pd.DataFrame(unique_issues, columns=['unique_issues'])

# Display the new DataFrame with unique values
print(unique_issues_df)

          unique_issues
0              military
1   banking and finance
2               economy
3                energy
4           environment
5    indigenous peoples
6                  guns
7              policing
8           legislative
9             education
10               racism
11           presidency
12       transportation
13      foreign affairs
14       women's rights
15            democracy
16            judiciary
17                labor
18          development
19          immigration
20           healthcare
21     criminal justice
22  reproductive rights
23              lgbtqia
24                drugs
25             religion
26         civil rights
27        animal rights
28      sexual violence
29              housing
30                taxes
31              science
32           patriotism
33    disability rights
34               sports
35          free speech
36           corruption
37                covid

In [ ]:
unique_issues_df.to_csv('Output/unique issues.csv', index = False)

In [ ]:
# Concatenate the new columns with the original DataFrame
data = pd.concat([data, split_issues], axis=1)

In [ ]:
data.to_csv('Output/ccc_data_including_issues.csv', index = False)

In [ ]:
data.columns

Index(['date', 'bigevent', 'bydate', 'locality', 'state', 'location_detail',
       'online', 'type', 'title', 'macroevent',
       ...
       'issues6', 'issues7', 'issues8', 'issues9', 'issues10', 'issues11',
       'issues12', 'issues13', 'issues14', 'issues15'],
      dtype='object', length=106)